---
spec:
  template:
    spec:
      containers:
      - name: deck
        args:
        - --config-path=/etc/config/config.yaml
        #- --tide-url=http://tide/
        - --hook-url=http://hook:8888/plugin-help
        - --job-config-path=/etc/job-config
        - --spyglass
        - --plugin-config=/etc/plugins/plugins.yaml
        - --github-token-path=/etc/github/oauth
        #- --redirect-http-to=status.build.kyma-project.io
        #- --build-cluster=/etc/cluster/cluster.yaml
        volumeMounts:
        - mountPath: /static/extensions
          name: branding
          readOnly: true
      volumes:
      - configMap:
          defaultMode: 420
          name: branding
        name: branding
