---
plugins:
  kyma-test-infra-dev:
    - cat
    - trigger
  kyma-test-infra-dev/test-infra:
    - config-updater

config_updater:
  config_file: prow/config.yaml
  plugin_file: prow/plugins.yaml
  maps:
    prow/jobs/**/*.yaml:
      name: job-config
    prow/config.yaml:
      name: config
    prow/plugins.yaml:
      name: plugins

triggers:
- repos:
  - kyma-test-infra-dev
  #trusted_org: kyma-test-infra-dev
  only_org_members: true
  ignore_ok_to_test: true
  elide_skipped_contexts: false